services:
  postgres:
    image: postgres:alpine
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - locomote

  app:
    build: ./Dockerfile
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - locomote
networks:
  locomote:
    driver: bridge