services:
  postgres:
    image: postgres:alpine
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - locomote

  app:
    build: ./Dockerfile
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - locomote
  postgres-admin:
    image: dpage/pgadmin4:latest
    depends_on:
      - postgres
    ports:
      - "5050:80"
    networks:
      - locomote
    env_file:
      - .env

   
networks:
  locomote:
    driver: bridge